### ISSUE TITLE
Configure ModSecurity to allow IP addresses as server name and [BUG] impossible to create a custom configuration on UI

### ISSUE THREAD

**Issue by weizhuangzhi** [bunkerity/bunkerweb#622]
/etc/bunkerweb/variables.env
```
DNS_RESOLVERS=8.8.8.8 8.8.4.4
HTTP_PORT=80
HTTPS_PORT=443
API_LISTEN_IP=127.0.0.1
SERVER_NAME=192.168.144.6
MULTISITE=yes

192.168.144.6_USE_UI=yes
192.168.144.6_USE_REVERSE_PROXY=yes
192.168.144.6_REVERSE_PROXY_URL=/manage
192.168.144.6_REVERSE_PROXY_HOST=http://127.0.0.1:7000
192.168.144.6_INTERCEPTED_ERROR_CODES=400 404 405 413 429 500 501 502 503 504
```
When the UI is turned on and the default settings are adopted, 403 Forbidden will appear when adding the mysetting.conf file in the /etc/bunkerweb/configs/http/192.168.144.6/ directory on the configs page.

/var/log/bunkerweb/error.log
```
2023/09/07 14:04:59 [error] 15439#15439: *8 [DNSBL] dnsbl check for xbl.spamhaus.org failed, context: ngx.timer
2023/09/07 14:04:59 [error] 15439#15439: *8 [DNSBL] dnsbl check for sbl.spamhaus.org failed, context: ngx.timer
2023/09/07 14:04:59 [notice] 15439#15439: *8 [DNSBL] dnsbl check for problems.dnsbl.sorbs.net is successful, context: ngx.timer
2023/09/07 14:05:00 [error] 15439#15439: *8 [UTILS] error while doing A DNS query for 2.0.0.127.bl.blocklist.de : failed to receive reply from UDP server 8.8.4.4:53: timeout, context: ngx.timer
2023/09/07 14:05:00 [error] 15439#15439: *8 [DNSBL] dnsbl check for bl.blocklist.de failed, context: ngx.timer
2023/09/07 14:05:00 [notice] 15439#15439: *8 [INIT-WORKER] BunkerWeb is ready to fool hackers ! 🚀, context: ngx.timer
2023/09/07 14:05:04 [warn] 15440#15440: *24 ModSecurity: Warning. Matched "Operator `Rx' with parameter `^[\d.:]+$' against variable `REQUEST_HEADERS:Host' (Value: `192.168.144.6' ) [file "/usr/share/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "719"] [id "920350"] [rev ""] [msg "Host header is a numeric IP address"] [data "192.168.144.6"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "PCI/6.5.10"] [hostname "192.168.144.6"] [uri "/manage/configs"] [unique_id "169406670493.425967"] [ref "o0,13v35,13"], client: 192.168.188.250, server: 192.168.144.6, request: "GET /manage/configs HTTP/1.1", host: "192.168.144.6", referrer: "http://192.168.144.6/manage/configs"
2023/09/07 14:05:04 [warn] 15440#15440: *24 ModSecurity: Warning. Matched "Operator `Rx' with parameter `^[\d.:]+$' against variable `REQUEST_HEADERS:Host' (Value: `192.168.144.6' ) [file "/usr/share/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "719"] [id "920350"] [rev ""] [msg "Host header is a numeric IP address"] [data "192.168.144.6"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "PCI/6.5.10"] [hostname "192.168.144.6"] [uri "/manage/login"] [unique_id "16940667042.491365"] [ref "o0,13v58,13"], client: 192.168.188.250, server: 192.168.144.6, request: "GET /manage/login?next=%2Fmanage%2Fconfigs HTTP/1.1", host: "192.168.144.6", referrer: "http://192.168.144.6/manage/configs"
2023/09/07 14:05:10 [warn] 15440#15440: *24 ModSecurity: Warning. Matched "Operator `Rx' with parameter `^[\d.:]+$' against variable `REQUEST_HEADERS:Host' (Value: `192.168.144.6' ) [file "/usr/share/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "719"] [id "920350"] [rev ""] [msg "Host header is a numeric IP address"] [data "192.168.144.6"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "PCI/6.5.10"] [hostname "192.168.144.6"] [uri "/manage/login"] [unique_id "169406671014.536261"] [ref "o0,13v34,13"], client: 192.168.188.250, server: 192.168.144.6, request: "POST /manage/login HTTP/1.1", host: "192.168.144.6", referrer: "http://192.168.144.6/manage/login?next=%2Fmanage%2Fconfigs"
2023/09/07 14:05:11 [warn] 15440#15440: *24 ModSecurity: Warning. Matched "Operator `Rx' with parameter `^[\d.:]+$' against variable `REQUEST_HEADERS:Host' (Value: `192.168.144.6' ) [file "/usr/share/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "719"] [id "920350"] [rev ""] [msg "Host header is a numeric IP address"] [data "192.168.144.6"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "PCI/6.5.10"] [hostname "192.168.144.6"] [uri "/manage/loading"] [unique_id "169406671124.712727"] [ref "o0,13v56,13"], client: 192.168.188.250, server: 192.168.144.6, request: "GET /manage/loading?next=/manage/configs HTTP/1.1", host: "192.168.144.6", referrer: "http://192.168.144.6/manage/login?next=%2Fmanage%2Fconfigs"
2023/09/07 14:05:11 [warn] 15440#15440: *24 ModSecurity: Warning. Matched "Operator `Rx' with parameter `^[\d.:]+$' against variable `REQUEST_HEADERS:Host' (Value: `192.168.144.6' ) [file "/usr/share/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "719"] [id "920350"] [rev ""] [msg "Host header is a numeric IP address"] [data "192.168.144.6"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "PCI/6.5.10"] [hostname "192.168.144.6"] [uri "/manage/check_reloading"] [unique_id "169406671150.735232"] [ref "o0,13v64,13"], client: 192.168.188.250, server: 192.168.144.6, request: "GET /manage/check_reloading?next=/manage/configs HTTP/1.1", host: "192.168.144.6", referrer: "http://192.168.144.6/manage/loading?next=/manage/configs"
2023/09/07 14:05:11 [warn] 15440#15440: *24 ModSecurity: Warning. Matched "Operator `Rx' with parameter `^[\d.:]+$' against variable `REQUEST_HEADERS:Host' (Value: `192.168.144.6' ) [file "/usr/share/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "719"] [id "920350"] [rev ""] [msg "Host header is a numeric IP address"] [data "192.168.144.6"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "PCI/6.5.10"] [hostname "192.168.144.6"] [uri "/manage/configs"] [unique_id "169406671184.055299"] [ref "o0,13v35,13"], client: 192.168.188.250, server: 192.168.144.6, request: "GET /manage/configs HTTP/1.1", host: "192.168.144.6", referrer: "http://192.168.144.6/manage/loading?next=/manage/configs"
2023/09/07 14:05:23 [warn] 15440#15440: *24 ModSecurity: Warning. Matched "Operator `Rx' with parameter `^[\d.:]+$' against variable `REQUEST_HEADERS:Host' (Value: `192.168.144.6' ) [file "/usr/share/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "719"] [id "920350"] [rev ""] [msg "Host header is a numeric IP address"] [data "192.168.144.6"] [severity "4"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272"] [tag "PCI/6.5.10"] [hostname "192.168.144.6"] [uri "/manage/configs"] [unique_id "169406672397.413296"] [ref "o0,13v36,13"], client: 192.168.188.250, server: 192.168.144.6, request: "POST /manage/configs HTTP/1.1", host: "192.168.144.6", referrer: "http://192.168.144.6/manage/configs"
2023/09/07 14:05:23 [warn] 15440#15440: *24 ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?:\bhttp/\d|<(?:html|meta)\b)' against variable `ARGS:path' (Value: `/etc/bunkerweb/configs/http/192.168.144.6/' ) [file "/usr/share/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-921-PROTOCOL-ATTACK.conf"] [line "89"] [id "921130"] [rev ""] [msg "HTTP Response Splitting Attack"] [data "Matched Data: http/1 found within ARGS:path: /etc/bunkerweb/configs/http/192.168.144.6/"] [severity "2"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272/220/34"] [hostname "192.168.144.6"] [uri "/manage/configs"] [unique_id "169406672397.413296"] [ref "o23,6v1035,42t:urlDecodeUni,t:htmlEntityDecode,t:lowercase"], client: 192.168.188.250, server: 192.168.144.6, request: "POST /manage/configs HTTP/1.1", host: "192.168.144.6", referrer: "http://192.168.144.6/manage/configs"
2023/09/07 14:05:23 [error] 15440#15440: *24 [client 192.168.188.250] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:ANOMALY_SCORE' (Value: `8' ) [file "/usr/share/bunkerweb/core/modsecurity/files/coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "81"] [id "949110"] [rev ""] [msg ""] [data ""] [severity "0"] [ver "OWASP_CRS/3.3.4"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "192.168.144.6"] [uri "/manage/configs"] [unique_id "169406672397.413296"] [ref ""], client: 192.168.188.250, server: 192.168.144.6, request: "POST /manage/configs HTTP/1.1", host: "192.168.144.6", referrer: "http://192.168.144.6/manage/configs"
```

Looking at the logs, it may be that DNSBL and ModSecurity are blocking file writing.
Disable DNSBL and ModSecurity etc and retest, occasionally 500 errors appear

```
2023/09/07 14:15:02 [error] 16092#16092: *12 [INIT-WORKER] bunkernet:init_worker() call failed : error while sending request to API : status code != 200, context: ngx.timer
```

The file will never be written successfully, what is the reason?

**Comment by TheophileDiot** [comment]
Hi @weizhuangzhi thank you for opening this issue, we will add a rule to avoid this false-positive in the future 😁

**Comment by TheophileDiot** [comment]
Hi @weizhuangzhi, if you look at the Modsecurity logs you'll see that it doesn't like that you put an ip address as a `SERVER_NAME`. it is linked to this rule specifically -> https://github.com/bunkerity/bunkerweb/blob/fc1c81ce2013e8d7c612c22262424bece51811e9/src/common/core/modsecurity/files/coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L708-L736.

This is not a much of bug but more a misconfiguration. If you want to allow IP addresses as server names you should add an override to ignore this rule -> `id:920350`

```conf
SecRuleRemoveById 920350
```

**Comment by weizhuangzhi** [comment]
@TheophileDiot thank you for your reply！

**Comment by TheophileDiot** [comment]
Anytime !

**Comment by weizhuangzhi** [comment]
I changed IP access to domain name access, but files still cannot be added to SERVICE MANAGER. The page returns a 500 error, and no information is recorded in /var/log/bunkerweb/error.log.
Are there any other reasons for this problem?

**Comment by TheophileDiot** [comment]
Interesting. Do you have logs with the UI maybe ? Else I'll check what could be the issue and let you know.

**Comment by TheophileDiot** [comment]
@weizhuangzhi are you using Fedora Sever 38 like in the other issues as well ?

**Comment by weizhuangzhi** [comment]
Yes, they were all tested in the same environment
I don't know much about python. Is there a way to display the detailed error message of 500? I can continue to test it, or do I need to provide other information?

**Comment by TheophileDiot** [comment]
Don't worry @weizhuangzhi, I'll test it myself and let you know
If you want more logs with the UI you'll need to use the dev environment instead of the prod one by editing this line in the file `/usr/share/bunkerweb/scripts/bunkerweb-ui.sh` --> https://github.com/bunkerity/bunkerweb/blob/fc1c81ce2013e8d7c612c22262424bece51811e9/src/linux/scripts/bunkerweb-ui.sh#L17
And replacing it with this one --> `python3 -m flask --app main:app run --host=127.0.0.1 --port=7000`
**MPORTANT: ⚠️ Do not use it in production as it will return the errors to the clients ⚠️**

**Comment by weizhuangzhi** [comment]
OK，thanks
I just removed 500 in /etc/bunkerweb/variables.env config
bunker6.tt_INTERCEPTED_ERROR_CODES=400 404 405 413 429 501 502 503 504

I got a "Redirecting..." page
Redirecting...
You should be redirected automatically to the target URL: /manage/loading?next=/manage/configs. If not, click the link.

I cleared all five files in the /var/log/bunkerweb directory. After adding the files, there are only two access logs in the access.log and ui-access.log files, and there are no records in other files.

**Comment by TheophileDiot** [comment]
@weizhuangzhi, does the command `journalctl -u bunkerweb-ui --no-pager` gives you anything ?

**Comment by weizhuangzhi** [comment]
```
9月 08 14:21:27 fedora38 bunkerweb-ui.sh[4052]: [2023-09-08 14:21:27] - main - ℹ️  - Database connection established
9月 08 14:21:27 fedora38 bunkerweb-ui.sh[4052]: [2023-09-08 14:21:27] - main - ℹ️  - Database is ready
9月 08 14:28:20 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:20] - GENERATOR - ℹ️  - Save config started ...
9月 08 14:28:20 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:20] - GENERATOR - ℹ️  - Settings : /usr/share/bunkerweb/settings.json
9月 08 14:28:20 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:20] - GENERATOR - ℹ️  - Core : /usr/share/bunkerweb/core
9月 08 14:28:20 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:20] - GENERATOR - ℹ️  - Plugins : /etc/bunkerweb/plugins
9月 08 14:28:20 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:20] - GENERATOR - ℹ️  - Init : False
9月 08 14:28:20 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:20] - GENERATOR - ℹ️  - Checking arguments ...
9月 08 14:28:20 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:20] - GENERATOR - ℹ️  - Variables : /tmp/1b230bfd-14bf-4ceb-aa18-503725121faa.env
9月 08 14:28:20 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:20] - GENERATOR - ℹ️  - Computing config ...
9月 08 14:28:20 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:20] - GENERATOR - ℹ️  - Database connection established
9月 08 14:28:20 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:20] - GENERATOR - ℹ️  - Database is already initialized, skipping ...
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Config successfully saved to database
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4219]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Config saver successfully executed !
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Save config started ...
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Settings : /usr/share/bunkerweb/settings.json
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Core : /usr/share/bunkerweb/core
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Plugins : /etc/bunkerweb/plugins
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Init : False
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Checking arguments ...
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Variables : /tmp/e4e1d96a-36c4-462f-b87a-1785073f453b.env
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Computing config ...
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Database connection established
9月 08 14:28:21 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:21] - GENERATOR - ℹ️  - Database is already initialized, skipping ...
9月 08 14:28:22 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:22] - GENERATOR - ℹ️  - Config successfully saved to database
9月 08 14:28:22 fedora38 bunkerweb-ui.sh[4252]: [2023-09-08 14:28:22] - GENERATOR - ℹ️  - Config saver successfully executed !
```

**Comment by TheophileDiot** [comment]
Interesting, and you managed to reproduce your error ?

**Comment by weizhuangzhi** [comment]
Tried it again, still the same error.
There are no new entries in the journalctl log.

**Comment by TheophileDiot** [comment]
Interesting, I'll currently building a .deb file to test it myself, thank you for the help 😁

**Comment by weizhuangzhi** [comment]
I'm missing something:
When the 500 page appears, return to the previous page on the browser and you will see a message in the Messages of the Web UI:
```
Error
/etc/bunkerweb/configs/http/ doesn't exist
```

This directory does not exist. The /etc/bunkerweb/configs directory is empty after default installation. I hope this will help you.

**Comment by TheophileDiot** [comment]
Thank you :pray:

**Comment by TheophileDiot** [comment]
I think it's a mix between permissions issues and missing folders, try creating the folders manually and executing the commands :
```shell
sudo chown -R nginx:nginx /etc/bunkerweb/
sudo chmod -R 770 /etc/bunkerweb/```

**Comment by TheophileDiot** [comment]
Just tested it and that did the trick, it'll be automatically fixed in the next version, thanks again for this issue.

**Comment by weizhuangzhi** [comment]
There has been some progress on this issue.
sudo chown -R nginx:nginx /etc/bunkerweb/
sudo chmod -R 770 /etc/bunkerweb/
Still the same error after performing the operation
I manually created the /etc/bunkerweb/configs/http/bunker6.tt/ folder and granted permissions again, and finally I can write files!

**Comment by fl0ppy-d1sk** [comment]
Hey @weizhuangzhi,

It should be fixed in the last [1.5.2 version](https://github.com/bunkerity/bunkerweb/releases/tag/v1.5.2). Feel free to open a new issue if needed.
